# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Parham Kazemi
description: >- # this means to ignore newlines until "baseurl:"
  Parham's personal web page
baseurl: "" # the subpath of the site
url: "https://parham-k.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: CV
    - name: Projects
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Personal
      value: pkazemi3@gmail.com
      icon: fa-solid fa-envelope-open-text
    - type: email
      name: Work
      value: pkazemi@bcgsc.ca
      icon: fa-solid fa-envelope-open-text
  follow:
    - type: twitter
      name: Twitter/X
      link: http://twitter.com/parham_kzm
      username: "@parham_kzm"
      icon: fa-brands fa-x-twitter
    - type: scholar
      name: Google Scholar
      link: https://scholar.google.com/citations?user=-X4UY5QAAAAJ
      icon: fa-brands fa-google-scholar
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/p-kazemi
      icon: fa-brands fa-linkedin-in
    - type: github
      name: GitHub
      link: http://github.com/parham-k
      icon: fa-brands fa-github
    - type: instagram
      name: Instagram
      link: https://www.instagram.com/parham._.kazemi
      icon: fa-brands fa-instagram
    - type: unsplash
      name: Unsplash
      link: https://unsplash.com/@parham_kzm
      icon: fa-brands fa-unsplash

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
